// src/component/StockItem.vue
<script setup lang="ts">
import type { Stock } from '@/api/BaiDuStockApi'
import ExchangeTag from '@/component/ExchangeTag.vue'
import StockChart from '@/component/StockChart.vue'
import { useStockQuotation } from '@/hook/useStockQuotation'
import { computed, type PropType, ref } from 'vue'

const props = defineProps({
  stock: {
    type: Object as PropType<Stock>,
    required: true,
  },
})
const stockChartRef = ref<InstanceType<typeof StockChart>>()
const chartId = computed(() => {
  return `chart_${props.stock.code}`
})
const code = ref(props.stock.code)
const { isUp, color } = useStockQuotation(code, { onNewData: (data) => {
  stockChartRef.value?.update(data, isUp.value)
}, group: props.stock.type == 'index' ? 'quotation_index_fiveday' : 'quotation_minute_ab' })
</script>

<template>
  <div class="stock-item flex items-center gap-2">
    <div class="flex flex-col justify-between gap-1">
      <div class="stock-title">
        {{ stock.name }}
      </div>
      <div class="info flex gap-1">
        <ExchangeTag :text=" stock.exchange " />
        {{ stock.code }}
      </div>
    </div>
    <StockChart :id="chartId" ref="stockChartRef" class="ml-auto" :height="25" />
    <span class="stock-price">{{ Number.parseFloat(stock.price).toFixed(2) }}</span>
    <span class="stock-change" :style="{ backgroundColor: color }">
      {{ stock.ratio }}
    </span>
  </div>
</template>

<style scoped>
.info{
  font-size: 0.7rem;
}

.stock-item{
  width: 100%;
}

.stock-title{
  width: 7rem;
  white-space: nowrap;
  font-size: 1rem;
  text-overflow: ellipsis;
  overflow: hidden;
  font-weight: bold;
}

.stock-change{
  border-radius: 4px;
  color: white;
  height: 1.5rem;
  width: 4rem;
  font-size: 0.9rem;
  display: flex;
  align-items: center;
  justify-content: center;
  justify-items: center;
}

.stock-price{
  width: 3.5rem;
}

.chart{
  width: 60px;
  height: 25px;
}
</style>

// src/components/stock-item.tsx
import * as React from 'react'
import { TrendingUp, TrendingDown } from 'lucide-react'
import type { Stock } from '@/model/stock'
import { ExchangeTag } from '@/components/exchange-tag'
import { useStockColorStore } from '@/store/use-stock-color-store'
import { cn } from '@/lib/utils'

interface StockItemProps {
  stock: Stock
  onClick?: () => void
  className?: string
}

export function StockItem({ stock, onClick, className }: StockItemProps) {
  const { getColorByValue } = useStockColorStore()

  const ratioValue = Number(stock.ratio?.replace('%', '') || 0)
  const isUp = stock.increase?.startsWith('+') || ratioValue >= 0
  const colorConfig = getColorByValue(ratioValue)

  const currentPrice = Number.parseFloat(stock.price || '0')

  return (
    <div
      className={cn(
        'stock-item flex items-center gap-2 w-full cursor-pointer hover:bg-accent/50 rounded-md p-1 transition-colors',
        className,
      )}
      onClick={onClick}
    >
      <div className="flex flex-col justify-between gap-1 min-w-0">
        <div className="stock-title w-[7rem] whitespace-nowrap text-[0.9rem] font-bold truncate overflow-hidden">
          {stock.name}
        </div>
        <div className="info flex items-center gap-1 text-[0.7rem] text-muted-foreground">
          <ExchangeTag exchange={stock.exchange} />
          <span className="truncate">{stock.code}</span>
        </div>
      </div>

      <div className="ml-auto flex items-center gap-2">
        <span className="stock-price w-[3.5rem] text-right font-medium tabular-nums">
          {currentPrice.toFixed(2)}
        </span>
        <span
          className={cn(
            'stock-change inline-flex items-center justify-center rounded h-6 w-16 text-[0.8rem] text-white font-medium',
            isUp ? 'bg-up-color' : 'bg-down-color',
          )}
          style={{ backgroundColor: colorConfig.color }}
        >
          {isUp ? <TrendingUp className="h-3 w-3 mr-0.5" /> : <TrendingDown className="h-3 w-3 mr-0.5" />}
          {stock.ratio}
        </span>
      </div>
    </div>
  )
}
